# Providers compile against this fork's source interface, never a binary ABI.
function(xui_lab_add_subject_provider)
  cmake_parse_arguments(PROVIDER "" "REGISTER" "SOURCES" ${ARGN})
  if (NOT PROVIDER_REGISTER MATCHES "^[A-Za-z_][A-Za-z_0-9]*$" OR NOT PROVIDER_SOURCES OR PROVIDER_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "xui_lab_add_subject_provider requires REGISTER <function> SOURCES <files...>")
  endif ()
  get_property(registrations TARGET xui-lab PROPERTY XUI_LAB_REGISTRATIONS)
  if (PROVIDER_REGISTER IN_LIST registrations)
    message(FATAL_ERROR "Duplicate XUI Lab provider: ${PROVIDER_REGISTER}")
  endif ()
  set_property(TARGET xui-lab APPEND PROPERTY XUI_LAB_REGISTRATIONS "${PROVIDER_REGISTER}")
  target_sources(xui-lab PRIVATE ${PROVIDER_SOURCES})
endfunction()

get_property(xui_lab_providers TARGET ${VIEWER_BINARY_NAME} PROPERTY XUI_LAB_SUBJECT_PROVIDERS)
foreach (provider IN LISTS xui_lab_providers)
  include("${provider}")
endforeach ()

set(xui_lab_provider_code "#include \"llviewerprecompiledheaders.h\"\n#include \"xui_lab_types.h\"\nnamespace xui_lab {\n")
get_property(xui_lab_registrations TARGET xui-lab PROPERTY XUI_LAB_REGISTRATIONS)
foreach (registration IN LISTS xui_lab_registrations)
  string(APPEND xui_lab_provider_code "void ${registration}(std::vector<ExtensionSubject>&);\n")
endforeach ()
string(APPEND xui_lab_provider_code "void appendExtensionSubjects(std::vector<ExtensionSubject>& subjects) {\n(void)subjects;\n")
foreach (registration IN LISTS xui_lab_registrations)
  string(APPEND xui_lab_provider_code "${registration}(subjects);\n")
endforeach ()
string(APPEND xui_lab_provider_code "}\n}\n")
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/xui_lab_providers.cpp" CONTENT "${xui_lab_provider_code}")
target_sources(xui-lab PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/xui_lab_providers.cpp")
