#pragma once

#include <functional>
#include <memory>
#include <string>
#include <string_view>
#include <variant>
#include <vector>

class LLFloater;
class LLSD;

namespace xui_lab
{
using EffectRecorder = std::function<void(const LLSD&)>;

// Created after LLUI initialization and destroyed before the GL context.
class SubjectFixture
{
public:
    virtual ~SubjectFixture()     = default;
    virtual void registerWindow() = 0;
    virtual void opened(LLFloater&) {}
    virtual void beforeFrame(LLFloater&) {}
};

struct ExtensionSubject
{
    std::string                                                    name;
    std::vector<std::string>                                       capabilities;
    std::function<std::unique_ptr<SubjectFixture>(EffectRecorder)> makeFixture;
};

enum class BuiltinSubject
{
    TestWidgets,
    InventoryExplorer,
    Preferences
};
using Subject = std::variant<BuiltinSubject, const ExtensionSubject*>;

// Generated by CMake from the linked providers. No viewer work happens here.
void                                               appendExtensionSubjects(std::vector<ExtensionSubject>& subjects);
[[nodiscard]] const std::vector<ExtensionSubject>& extensionSubjects();
[[nodiscard]] std::string_view                     subjectName(const Subject& subject);
} // namespace xui_lab
