import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";

const inspectorRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(inspectorRoot, "../schemas/inspector.openapi.json");
const generatedRoot = resolve(inspectorRoot, "src/generated");
const typesPath = resolve(generatedRoot, "inspector-api.ts");
const hashPath = resolve(generatedRoot, "openapi-hash.ts");
const validatorsJsPath = resolve(generatedRoot, "validators.js");
const validatorsDtsPath = resolve(generatedRoot, "validators.d.ts");
const check = process.argv.includes("--check");
const generatedFiles = [
  ["inspector-api.ts", typesPath],
  ["openapi-hash.ts", hashPath],
  ["validators.js", validatorsJsPath],
  ["validators.d.ts", validatorsDtsPath],
];

function generate(outputRoot) {
  const outputTypes = resolve(outputRoot, "inspector-api.ts");
  const outputHash = resolve(outputRoot, "openapi-hash.ts");
  execFileSync(
    resolve(inspectorRoot, "node_modules/.bin/openapi-typescript"),
    [schemaPath, "-o", outputTypes],
    {
      stdio: "inherit",
    },
  );
  execFileSync(
    resolve(inspectorRoot, "node_modules/.bin/biome"),
    ["format", "--write", outputTypes],
    {
      stdio: "inherit",
    },
  );
  const digest = createHash("sha256").update(readFileSync(schemaPath)).digest("hex");
  writeFileSync(outputHash, `export const OPENAPI_HASH = "${digest}";\n`);
  generateValidators(resolve(outputRoot, "validators.js"), resolve(outputRoot, "validators.d.ts"));
}

function generateValidators(outputJs, outputDts) {
  const openapi = JSON.parse(readFileSync(schemaPath, "utf8"));
  // unicode: false keeps standalone output free of require("ajv/dist/runtime/ucs2length").
  // The generated module must not call Function or eval; FastAPI CSP is script-src 'self'.
  const ajv = new Ajv({
    allErrors: true,
    strict: false,
    unicode: false,
    code: { source: true, esm: true },
  });
  const schemaRoot = { components: openapi.components };
  const specs = {
    validateState: {
      $id: "https://xui-lab.local/validateState.json",
      ...schemaRoot,
      $ref: "#/components/schemas/InspectorStateDocument",
    },
    validateActionResponse: {
      $id: "https://xui-lab.local/validateActionResponse.json",
      ...schemaRoot,
      $ref: "#/components/schemas/InspectorActionAccepted",
    },
    validateProblem: {
      $id: "https://xui-lab.local/validateProblem.json",
      ...schemaRoot,
      $ref: "#/components/schemas/InspectorProblemDetails",
    },
    validateEvent: {
      $id: "https://xui-lab.local/validateEvent.json",
      ...openapi.paths["/api/v1/events"].get.responses["200"].content["text/event-stream"].schema,
    },
    validateSnapshot: {
      $id: "https://xui-lab.local/validateSnapshot.json",
      ...schemaRoot,
      $ref: "#/components/schemas/InspectorCaptureSnapshot",
    },
  };
  const ids = {};
  for (const [name, schema] of Object.entries(specs)) {
    ajv.compile(schema);
    ids[name] = schema.$id;
  }
  const code = standaloneCode(ajv, ids);
  if (code.includes("Function(") || code.includes("eval(") || code.includes("require(")) {
    throw new Error("standalone validators must not evaluate or require code at runtime");
  }
  writeFileSync(outputJs, `/* Generated by scripts/generate-api.mjs. Do not edit. */\n${code}`);
  writeFileSync(
    outputDts,
    `export type OpenApiValidator = ((data: unknown) => boolean) & {
  errors: ReadonlyArray<{
    instancePath?: string;
    message?: string;
  }> | null;
};

export const validateState: OpenApiValidator;
export const validateActionResponse: OpenApiValidator;
export const validateProblem: OpenApiValidator;
export const validateEvent: OpenApiValidator;
export const validateSnapshot: OpenApiValidator;
`,
  );
  execFileSync(
    resolve(inspectorRoot, "node_modules/.bin/biome"),
    ["format", "--write", outputDts],
    {
      stdio: "inherit",
    },
  );
}

if (check) {
  const temporaryRoot = mkdtempSync(resolve(tmpdir(), "xui-lab-openapi-"));
  try {
    generate(temporaryRoot);
    for (const [relative, actual] of generatedFiles) {
      const expected = resolve(temporaryRoot, relative);
      if (readFileSync(actual, "utf8") !== readFileSync(expected, "utf8")) {
        throw new Error(`${actual} is stale; run: npm run generate:api --prefix inspector`);
      }
    }
  } finally {
    rmSync(temporaryRoot, { recursive: true, force: true });
  }
} else {
  generate(generatedRoot);
}
